# Generated by Django 2.0.6 on 2018-06-12 20:46

import course.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180612_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ownerList',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ownerSummary',
        ),
        migrations.AddField(
            model_name='list',
            name='file_l',
            field=models.FileField(default=django.utils.timezone.now, upload_to=course.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='file_s',
            field=models.FileField(default=django.utils.timezone.now, upload_to=course.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
