# Generated by Django 2.0.7 on 2018-07-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180702_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='course.Teacher'),
        ),
        migrations.AlterField(
            model_name='list',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='course.Teacher'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='course.Teacher'),
        ),
    ]
