# Generated by Django 2.0.6 on 2018-07-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180701_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
    ]
