# Generated by Django 2.0.6 on 2018-06-13 11:56

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180612_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='file_l',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='file_s',
        ),
        migrations.AddField(
            model_name='list',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=course.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='summary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=course.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='course.Tag'),
        ),
        migrations.AlterField(
            model_name='list',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='course.Tag'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
