# Generated by Django 2.0.6 on 2018-07-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180701_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
