# Generated by Django 2.0.6 on 2018-07-01 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180701_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='course.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='course.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='course.Teacher'),
            preserve_default=False,
        ),
    ]
