# Generated by Django 2.0.6 on 2018-06-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180629_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, to='course.Tag'),
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, to='course.Tag'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='course.Tag'),
        ),
    ]
