# Generated by Django 2.0.6 on 2018-06-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20180629_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='list',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='course.Course'),
        ),
    ]
