# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Comment')),
            ],
        ),
    ]
