# Generated by Django 2.0.6 on 2018-07-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180701_0302'),
        ('forum', '0002_auto_20180701_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='course.Course'),
        ),
    ]
