# Generated by Django 2.0.6 on 2018-06-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180612_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
