# Generated by Django 2.0.6 on 2018-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180612_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
    ]
