# Generated by Django 2.0.6 on 2018-06-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180613_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
    ]
