# Generated by Django 2.0.6 on 2018-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_post_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='forum.Tag'),
        ),
    ]
