# Generated by Django 2.0.7 on 2018-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180703_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/registration/pictures/default.png', upload_to='static/registration/pictures/'),
        ),
    ]
