# Generated by Django 2.0.6 on 2018-07-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180702_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='pictures/mclovin.png', upload_to='pictures'),
        ),
    ]
