# Generated by Django 2.0.7 on 2018-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180703_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/pictures/default.png', upload_to='profile/pictures/'),
        ),
    ]
