# Generated by Django 2.0.7 on 2018-07-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180703_1725'),
        ('registration', '0005_auto_20180703_1745'),
    ]

    operations = [
    ]
