# Generated by Django 2.0.6 on 2018-07-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='pictures/mclovin.png', upload_to='pictures/'),
        ),
    ]
