# Generated by Django 2.0.6 on 2018-07-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180702_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pictures/mclovin.png', upload_to='pictures/'),
        ),
    ]
