# Generated by Django 2.0.7 on 2018-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_merge_20180705_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/pictures/default.webp', upload_to='profile/pictures/'),
        ),
    ]
