# Generated by Django 2.0.7 on 2018-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_merge_20180704_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/pictures/default.png', upload_to='profile/pictures/'),
        ),
    ]
