# Generated by Django 2.0.7 on 2018-07-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180705_1825'),
        ('registration', '0007_auto_20180705_1821'),
        ('registration', '0007_auto_20180704_1810'),
    ]

    operations = [
    ]
