# Generated by Django 2.0.6 on 2018-07-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180702_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='registration/static/registration/pictures/default.png', upload_to='pictures/'),
        ),
    ]
