# Generated by Django 2.0.7 on 2018-07-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180705_2221'),
        ('registration', '0008_merge_20180705_2233'),
    ]

    operations = [
    ]
